# Generated by Django 4.2.1 on 2023-05-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_category', models.CharField(blank=True, max_length=50, null=True)),
                ('food_name', models.CharField(blank=True, max_length=50, null=True)),
                ('food_image', models.ImageField(blank=True, null=True, upload_to='food_images/')),
            ],
        ),
    ]
