# Generated by Django 4.2.1 on 2023-06-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FridgiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodListImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='foodlist_images/')),
            ],
        ),
    ]
