# Generated by Django 4.2.1 on 2023-05-09 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FridgiApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Operater',
            new_name='Food',
        ),
    ]
