# Generated by Django 4.2.1 on 2023-07-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FridgiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='last_updated',
            field=models.TimeField(auto_now=True),
        ),
    ]
