# Generated by Django 4.2.1 on 2023-07-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FridgiApp', '0002_alter_fooditem_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
