# Generated by Django 4.2.1 on 2023-07-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FridgiApp', '0004_testimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='capture_image/')),
            ],
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='TestImage',
        ),
        migrations.DeleteModel(
            name='TextScanner',
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='food_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='food_category',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='food_image',
        ),
        migrations.DeleteModel(
            name='Food_Category',
        ),
    ]
