# Generated by Django 4.2.1 on 2023-07-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FridgiApp', '0005_captureimage_delete_notification_delete_testimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
